"""Verified research, bibliography and evidence helpers."""

from .bibliography import (
    BibliographyDeduplicator,
    BibliographyValidation,
    BibliographyValidator,
    DeduplicationResult,
    canonical_url,
    deduplicate_bibliography,
    format_gost_bibliography,
    normalize_doi,
    normalize_isbn,
    valid_doi,
    valid_isbn,
    validate_bibliography_entry,
)
from .datasets import (
    CompositeDatasetDiscovery,
    DataCiteDatasetDiscovery,
    DatasetDiscoveryPort,
    DatasetSnapshot,
    DiscoveredDataset,
    ZenodoDatasetDiscovery,
)
from .evidence import EvidenceCoverage, EvidenceGraph, evidence_from_fragment, link_claim_evidence
from .scholarly import (
    CrossrefClient,
    DOIResolver,
    OfficialSourcePolicy,
    OpenAlexClient,
    ScholarlyDiscovery,
    ScholarlyRecord,
)
from .snapshots import SnapshotCaptureResult, SourceSnapshotStore
from .url_verifier import (
    HTTPResponse,
    HTTPTransport,
    PinnedHTTPTransport,
    SafeTarget,
    UnsafeURLError,
    URLFetchError,
    URLPolicy,
    URLVerificationError,
    URLVerificationResult,
    URLVerifier,
    normalize_url,
    verify_url,
)

__all__ = [
    "BibliographyDeduplicator",
    "BibliographyValidation",
    "BibliographyValidator",
    "CompositeDatasetDiscovery",
    "CrossrefClient",
    "DOIResolver",
    "DataCiteDatasetDiscovery",
    "DatasetDiscoveryPort",
    "DatasetSnapshot",
    "DeduplicationResult",
    "DiscoveredDataset",
    "EvidenceCoverage",
    "EvidenceGraph",
    "HTTPResponse",
    "HTTPTransport",
    "OfficialSourcePolicy",
    "OpenAlexClient",
    "PinnedHTTPTransport",
    "SafeTarget",
    "ScholarlyDiscovery",
    "ScholarlyRecord",
    "SnapshotCaptureResult",
    "SourceSnapshotStore",
    "URLFetchError",
    "URLPolicy",
    "URLVerificationError",
    "URLVerificationResult",
    "URLVerifier",
    "UnsafeURLError",
    "ZenodoDatasetDiscovery",
    "canonical_url",
    "deduplicate_bibliography",
    "evidence_from_fragment",
    "format_gost_bibliography",
    "link_claim_evidence",
    "normalize_doi",
    "normalize_isbn",
    "normalize_url",
    "valid_doi",
    "valid_isbn",
    "validate_bibliography_entry",
    "verify_url",
]
