"""Verified research, bibliography and evidence helpers."""

from .bibliography import (
    BibliographyDeduplicator,
    BibliographyValidation,
    BibliographyValidator,
    DeduplicationResult,
    canonical_url,
    deduplicate_bibliography,
    normalize_doi,
    normalize_isbn,
    valid_doi,
    valid_isbn,
    validate_bibliography_entry,
)
from .evidence import EvidenceCoverage, EvidenceGraph, evidence_from_fragment, link_claim_evidence
from .url_verifier import (
    HTTPResponse,
    HTTPTransport,
    PinnedHTTPTransport,
    SafeTarget,
    UnsafeURLError,
    URLFetchError,
    URLPolicy,
    URLVerificationError,
    URLVerificationResult,
    URLVerifier,
    normalize_url,
    verify_url,
)

__all__ = [
    "BibliographyDeduplicator",
    "BibliographyValidation",
    "BibliographyValidator",
    "DeduplicationResult",
    "EvidenceCoverage",
    "EvidenceGraph",
    "HTTPResponse",
    "HTTPTransport",
    "PinnedHTTPTransport",
    "SafeTarget",
    "URLFetchError",
    "URLPolicy",
    "URLVerificationError",
    "URLVerificationResult",
    "URLVerifier",
    "UnsafeURLError",
    "canonical_url",
    "deduplicate_bibliography",
    "evidence_from_fragment",
    "link_claim_evidence",
    "normalize_doi",
    "normalize_isbn",
    "normalize_url",
    "valid_doi",
    "valid_isbn",
    "validate_bibliography_entry",
    "verify_url",
]
