from __future__ import annotations

from pathlib import Path
from typing import Protocol

from papercraft.domain import (
    Artifact,
    BibliographyEntry,
    Calculation,
    Citation,
    Claim,
    Dataset,
    Evidence,
    FactRecord,
    GenerationRun,
    Manuscript,
    Project,
    ProjectBlueprint,
    QAReport,
    RequirementSet,
    RunEvent,
    Source,
    SourceFragment,
    StageRun,
)


class RepositoryPort(Protocol):
    def save_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project | None: ...
    def list_projects(self, *, limit: int = 100, offset: int = 0) -> list[Project]: ...
    def save_source(self, source: Source) -> None: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def list_sources(self, project_id: str, *, role: str | None = None) -> list[Source]: ...
    def save_fragment(self, fragment: SourceFragment) -> None: ...
    def list_fragments(self, source_id: str) -> list[SourceFragment]: ...
    def save_requirement_set(self, requirements: RequirementSet) -> None: ...
    def get_latest_requirement_set(self, project_id: str) -> RequirementSet | None: ...
    def save_blueprint(self, blueprint: ProjectBlueprint) -> None: ...
    def get_latest_blueprint(self, project_id: str) -> ProjectBlueprint | None: ...
    def save_manuscript(self, manuscript: Manuscript) -> None: ...
    def get_latest_manuscript(self, project_id: str) -> Manuscript | None: ...
    def save_run(self, run: GenerationRun) -> None: ...
    def get_run(self, run_id: str) -> GenerationRun | None: ...
    def list_runs(self, project_id: str) -> list[GenerationRun]: ...
    def save_stage(self, stage: StageRun) -> None: ...
    def get_stage(self, stage_id: str) -> StageRun | None: ...
    def list_stages(self, run_id: str) -> list[StageRun]: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def list_artifacts(self, project_id: str, *, run_id: str | None = None) -> list[Artifact]: ...
    def save_qa_report(self, report: QAReport) -> None: ...
    def get_latest_qa_report(self, run_id: str) -> QAReport | None: ...
    def append_event(self, event: RunEvent) -> int: ...
    def list_events(self, run_id: str, *, after_sequence: int = 0) -> list[tuple[int, RunEvent]]: ...
    def save_claim(self, claim: Claim) -> None: ...
    def list_claims(self, project_id: str) -> list[Claim]: ...
    def save_evidence(self, project_id: str, evidence: Evidence) -> None: ...
    def list_evidence(self, project_id: str) -> list[Evidence]: ...
    def save_bibliography_entry(self, project_id: str, entry: BibliographyEntry) -> None: ...
    def list_bibliography(self, project_id: str) -> list[BibliographyEntry]: ...
    def save_citation(self, project_id: str, citation: Citation) -> None: ...
    def list_citations(self, project_id: str) -> list[Citation]: ...
    def delete_citations(self, project_id: str) -> None: ...
    def clear_research_data(self, project_id: str, *, include_claims: bool = False) -> None: ...
    def clear_calculation_data(self, project_id: str) -> None: ...
    def save_fact(self, fact: FactRecord) -> None: ...
    def list_facts(self, project_id: str) -> list[FactRecord]: ...
    def save_dataset(self, dataset: Dataset) -> None: ...
    def list_datasets(self, project_id: str) -> list[Dataset]: ...
    def save_calculation(self, calculation: Calculation) -> None: ...
    def list_calculations(self, project_id: str) -> list[Calculation]: ...


class ArtifactStorePort(Protocol):
    def write_json(self, relative_path: str | Path, value: object) -> Path: ...
