from __future__ import annotations

from collections.abc import Collection
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Protocol

from papercraft.domain import (
    Artifact,
    BibliographyEntry,
    Calculation,
    Citation,
    Claim,
    Dataset,
    Evidence,
    FactRecord,
    GenerationRun,
    Manuscript,
    Project,
    ProjectBlueprint,
    QAReport,
    RemoteResource,
    RequirementSet,
    RevisionRecord,
    RunEvent,
    RunStatus,
    Source,
    SourceFragment,
    SourceSnapshot,
    StageRun,
    SubmissionRelease,
)


class RepositoryPort(Protocol):
    def save_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project | None: ...
    def list_projects(self, *, limit: int = 100, offset: int = 0) -> list[Project]: ...
    def save_source(self, source: Source) -> None: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def list_sources(self, project_id: str, *, role: str | None = None) -> list[Source]: ...
    def save_fragment(self, fragment: SourceFragment) -> None: ...
    def list_fragments(self, source_id: str) -> list[SourceFragment]: ...
    def clear_source_fragments(self, source_id: str) -> None: ...
    def save_source_snapshot(self, snapshot: SourceSnapshot) -> None: ...
    def list_source_snapshots(self, project_id: str) -> list[SourceSnapshot]: ...
    def save_requirement_set(self, requirements: RequirementSet) -> None: ...
    def get_latest_requirement_set(self, project_id: str) -> RequirementSet | None: ...
    def save_blueprint(self, blueprint: ProjectBlueprint) -> None: ...
    def get_latest_blueprint(self, project_id: str) -> ProjectBlueprint | None: ...
    def save_manuscript(self, manuscript: Manuscript) -> None: ...
    def replace_citations_and_save_manuscript(
        self, manuscript: Manuscript, citations: list[Citation]
    ) -> None: ...
    def get_latest_manuscript(self, project_id: str) -> Manuscript | None: ...
    def commit_section_override(
        self,
        manuscript: Manuscript,
        section_id: str,
        payload: str,
        *,
        baseline_payload: str | None = None,
    ) -> RevisionRecord: ...
    def list_section_revisions(self, project_id: str, section_id: str) -> list[RevisionRecord]: ...
    def get_section_revision_payload(self, project_id: str, revision_id: str) -> str | None: ...
    def commit_plan_override(
        self,
        blueprint: ProjectBlueprint,
        payload: str,
        *,
        baseline_payload: str | None = None,
        baseline_object_id: str | None = None,
    ) -> RevisionRecord: ...
    def list_plan_revisions(self, project_id: str) -> list[RevisionRecord]: ...
    def get_plan_revision_payload(self, project_id: str, revision_id: str) -> str | None: ...
    def save_run(self, run: GenerationRun) -> None: ...
    def save_run_preserving_control(
        self,
        run: GenerationRun,
        *,
        replace_metadata_keys: Collection[str] = (),
    ) -> GenerationRun: ...
    def add_run_usage(
        self,
        run_id: str,
        estimated_cost: Decimal,
        *,
        maximum_cost: Decimal | None = None,
    ) -> GenerationRun: ...
    def transition_run_status(
        self,
        run_id: str,
        *,
        status: RunStatus,
        allowed_from: set[RunStatus],
        finished_at: datetime | None = None,
    ) -> GenerationRun: ...
    def prepare_retry(
        self,
        run_id: str,
        *,
        stage_names: Collection[str],
        input_hash: str,
        reason: str,
        allowed_from: set[RunStatus],
        maximum_cost: Decimal | None,
    ) -> GenerationRun: ...
    def get_run(self, run_id: str) -> GenerationRun | None: ...
    def list_runs(self, project_id: str) -> list[GenerationRun]: ...
    def save_stage(self, stage: StageRun) -> None: ...
    def get_stage(self, stage_id: str) -> StageRun | None: ...
    def list_stages(self, run_id: str) -> list[StageRun]: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def list_artifacts(self, project_id: str, *, run_id: str | None = None) -> list[Artifact]: ...
    def save_qa_report(self, report: QAReport) -> None: ...
    def get_latest_qa_report(self, run_id: str) -> QAReport | None: ...
    def get_release(self, release_id: str) -> SubmissionRelease | None: ...
    def get_current_release(self, project_id: str) -> SubmissionRelease | None: ...
    def supersede_current_release(self, project_id: str, *, reason: str) -> Project: ...
    def finalize_submission_release(
        self,
        release: SubmissionRelease,
        *,
        finished_at: datetime,
    ) -> GenerationRun: ...
    def append_event(self, event: RunEvent) -> int: ...
    def list_events(self, run_id: str, *, after_sequence: int = 0) -> list[tuple[int, RunEvent]]: ...
    def save_claim(self, claim: Claim) -> None: ...
    def list_claims(self, project_id: str) -> list[Claim]: ...
    def save_evidence(self, project_id: str, evidence: Evidence) -> None: ...
    def list_evidence(self, project_id: str) -> list[Evidence]: ...
    def save_bibliography_entry(self, project_id: str, entry: BibliographyEntry) -> None: ...
    def replace_bibliography_entries(
        self, project_id: str, entries: list[BibliographyEntry]
    ) -> None: ...
    def list_bibliography(self, project_id: str) -> list[BibliographyEntry]: ...
    def save_citation(self, project_id: str, citation: Citation) -> None: ...
    def list_citations(self, project_id: str) -> list[Citation]: ...
    def delete_citations(self, project_id: str) -> None: ...
    def clear_research_data(self, project_id: str, *, include_claims: bool = False) -> None: ...
    def clear_calculation_data(self, project_id: str) -> None: ...
    def save_fact(self, fact: FactRecord) -> None: ...
    def list_facts(self, project_id: str) -> list[FactRecord]: ...
    def save_dataset(self, dataset: Dataset) -> None: ...
    def list_datasets(self, project_id: str) -> list[Dataset]: ...
    def save_calculation(self, calculation: Calculation) -> None: ...
    def list_calculations(self, project_id: str) -> list[Calculation]: ...
    def save_remote_resource(self, resource: RemoteResource) -> None: ...
    def list_remote_resources(self, run_id: str) -> list[RemoteResource]: ...


class ArtifactStorePort(Protocol):
    def write_json(self, relative_path: str | Path, value: object) -> Path: ...
